packages:
  - packages/*
  - apps/*
catalogs:
  dev:
    '@types/eslint': ^9.6.1
    automd: ^0.4.3
    changelogen: ^0.6.2
    eslint: ^9.39.2
    nuxt: ^3.21.1
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vue: ^3.5.28
    vue-router: ^4.6.4
  prod:
    '@eslint/js': ^9.39.2
    '@nuxt/eslint-plugin': ^0.7.6
    '@rushstack/eslint-patch': ^1.15.0
    '@typescript-eslint/eslint-plugin': ^8.55.0
    '@typescript-eslint/parser': ^8.55.0
    defu: ^6.1.4
    eslint-config-flat-gitignore: ^0.3.0
    eslint-flat-config-utils: ^0.4.0
    eslint-plugin-import-x: ^4.16.1
    eslint-plugin-jsdoc: ^50.8.0
    eslint-plugin-package-json: ^0.88.2
    eslint-plugin-pnpm: ^0.3.1
    eslint-plugin-vue: ^9.33.0
    eslint-plugin-yml: ^1.19.1
    jsonc-eslint-parser: ^2.4.2
    tslib: ^2.8.1
    vue-eslint-parser: ^9.4.3
    yaml-eslint-parser: ^1.3.2
