packages:
  - packages/*
  - apps/*
catalogs:
  dev:
    '@types/eslint': ^9.6.1
    automd: ^0.4.0
    changelogen: ^0.6.1
    eslint: ^9.26.0
    nuxt: ^3.17.1
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vue: ^3.5.13
    vue-router: ^4.5.1
  prod:
    '@eslint/js': ^9.26.0
    '@nuxt/eslint-plugin': ^0.7.6
    '@rushstack/eslint-patch': ^1.11.0
    '@typescript-eslint/eslint-plugin': ^8.31.1
    '@typescript-eslint/parser': ^8.31.1
    defu: ^6.1.4
    eslint-config-flat-gitignore: ^0.3.0
    eslint-flat-config-utils: ^0.4.0
    eslint-plugin-import-x: ^4.11.0
    eslint-plugin-jsdoc: ^50.6.11
    eslint-plugin-package-json: ^0.31.0
    eslint-plugin-pnpm: ^0.3.1
    eslint-plugin-vue: ^9.33.0
    eslint-plugin-yml: ^1.18.0
    jsonc-eslint-parser: ^2.4.0
    tslib: ^2.8.1
    vue-eslint-parser: ^9.4.3
    yaml-eslint-parser: ^1.3.0
