name: Upload coverage reports to Codecov
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: HugoRCD/shelve
